collections:
  projects:
    output: true
  myprojects-sk:
    output: true
  games:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "games"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

t:
  en:
    footerheader:  "Language"
    footercopy: "&copy Benjamín Muľár 2022, all rights reserved."
    people: "Cool people"
    highlighthome: "Hi! I'm Benjamín, high school student from Slovakia, currently learning web development, game dev & pixel art."
    postback: "Back"
    blogback: "/blog"
    learning: "Currently learning."
    projweb: "My only project is this web for now."
    projgamedev: "Games that I've made."
  sk:
    footerheader:  "Jazyk"
    footercopy: "&copy Benjamín Muľár 2022, všetky práva vyhradené."
    people: "Skvelý ľudia"
    highlighthome: "Ahoj! Ja som Benjamín, študent strednej školy na Slovensku, momentálne sa učiaci web development, herný vývoj & pixel art."
    postback: "Späť"
    blogback: "/sk/blog"
    learning: "Momentálne sa učím."
    projweb: "Môj jediný projekt je zatiaľ tento web."
    projgamedev: "Hry ktoré som vytvoril."

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

