collections:
  projects:
    output: false
  games:
    output: true
  websites:
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  - scope:
      path: "_games/sk"
    values:
      layout: "game"
      lang: "sk"
      permalink: "sk/games/:title.html"
  - scope:
      path: ""
    values:
      layout: "default"

t:
  en:
    footerheader:  "Language"
    footercopy: "&copy Benjamín Muľár 2022, all rights reserved."
    people: "Cool people"
    highlighthome: "Hi! I'm Benjamín, university student from Slovakia, currently learning web development & game dev."
    back: "Back"
    blogback: "/blog"
    learning: "Currently learning."
    projweb: "Websites that I've created."
    projgamedev: "Games that I've made."
    gameDownload: "Download"
    gameFullscreen: "Fullscreen"
    gameNote: "Note: You may need to refresh the page if the game is stuck/frozen on loading screen for a long time."
  sk:
    footerheader:  "Jazyk"
    footercopy: "&copy Benjamín Muľár 2022, všetky práva vyhradené."
    people: "Skvelí ľudia"
    highlighthome: "Ahoj! Ja som Benjamín, univerzitný študent na Slovensku, momentálne sa učiaci web development & herný vývoj."
    back: "Späť"
    blogback: "/sk/blog"
    learning: "Momentálne sa učím."
    projweb: "Webstránky, ktoré som vytvoril."
    projgamedev: "Hry, ktoré som vytvoril."
    gameDownload: "Stiahnuť"
    gameFullscreen: "Celá Obrazovka"
    gameNote: "Pozn.: Možno budete musieť obnoviť stránku, ak je hra zaseknutá/zamrznutá na obrazovke načítania dlhšie."


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

